### ISSUE TITLE
Encoder knobs

### ISSUE THREAD

**Issue by HartBlanc** [JW2586/waterfowl-keyboard-info#1]
Hi, I'm thinking about getting the waterfowl kit from mechboards but I've learned that that kit comes with a standard black encoder, where can I get the stylised encoder knobs shown in the gallery pictures?

**Comment by JW2586** [comment]
I got mine from Xentric Guitars, they come in a range of styles
https://xentricguitars.com/shop/ols/products/xentric-guitars-aurora-series-resin-guitar-parts-and-accessories/v/XG-AUR-139-6MM
