### ISSUE TITLE
Colemak-DH keymaps using QMK for atmega32u4

### ISSUE THREAD

**Issue by sushilbansal** [JW2586/waterfowl-keyboard-info#3]
Hi, do you have the Colemak-DH keymaps using QMK. I can't use the zmk as it is using atmega32u4 which is not supported by zmk. Thanks in advance.

**Comment by JW2586** [comment]
I don't have any pre-compiled QMK firmware using colemak-dh however you could make your own using the configurator [https://config.qmk.fm/#/waterfowl/LAYOUT](https://config.qmk.fm/#/waterfowl/LAYOUT) or Vial
